#version: '3.9' #ya no es necesaria

services:
  # construye una imagen usando el 
  app: 
    # apunta al dockerfile y toma el stage de dev
    build: 
    # Especifica la carpeta desde donde se ejecutarán las instrucciones del Dockerfile. esta es la raiz de mi aplicacion donde esta todo
      context: . 
      target: ${STAGE}  # Selecciona la etapa "prod", S i se cambia al stage de prod (Runner) de dockerfile ejecutara todos los pasos para cumplir con ese stage
      dockerfile: Dockerfile
    #command: ["sh", "-c", "npm run migrate && npm start"]
    # # command: yarn start:dev
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: express_typescript_boilerplate_2024
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV} 
      - PORT=${PORT}
      - HOST=${HOST}
      - PUBLIC_PATH=${PUBLIC_PATH}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - COMMON_RATE_LIMIT_WINDOW_MS=${COMMON_RATE_LIMIT_WINDOW_MS}
      - COMMON_RATE_LIMIT_MAX_REQUESTS=${COMMON_RATE_LIMIT_MAX_REQUESTS}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_DEFAULT_PASSWORD}
      - STAGE=${STAGE}

  db:
    container_name: clean_architecture_db
    image: postgres:14.15-alpine3.20
    restart: always #en caso de errores o paros, se reinicia
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  pgAdmin:
    container_name: pgAdmin_clean_architecture
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    volumes:
     - ./db/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - 8080:80
