#version: '3.9' #ya no es necesaria
 #se crea este docker compose para  no tener que ejecutar el siguiente comando, el cual se encarga de sobreescribir mi docker-compose.yml
 #docker compose -f docker-compose.yml -f production.yml up -d
 # correr solo este comando: docker compose -f docker-compose.prod.yml build y despues docker compose -f docker-compose.prod.yml up
 # Para decirle que construya solo un servicio de los que estan definidos, porque no queremos que la imagen de postgres se vaya en la generacion de la imagen: docker compose -f docker-compose.prod.yml build app




services:
  app: # construye una imagen usando el dockerfile
    build: # apunta al dockerfile y toma el stage de dev
      context: . # Especifica la carpeta desde donde se ejecutarán las instrucciones del Dockerfile. esta es la raiz de mi aplicacion donde esta todo
      target: ${STAGE}  # Selecciona la etapa "dev", S i se cambia al stage de prod (Runner) de dockerfile ejecutara todos los pasos para cumplir con ese stage
      dockerfile: Dockerfile
    #command: ["sh", "-c", "npm run migrate && npm start"]
    # # command: yarn start:dev
    image: devjohanadrian/clean_architecture_express_bolierplate:latest
    container_name: express_typescript_boilerplate_2024
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV} 
      - PORT=${PORT}
      - HOST=${HOST}
      - PUBLIC_PATH=${PUBLIC_PATH}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - COMMON_RATE_LIMIT_WINDOW_MS=${COMMON_RATE_LIMIT_WINDOW_MS}
      - COMMON_RATE_LIMIT_MAX_REQUESTS=${COMMON_RATE_LIMIT_MAX_REQUESTS}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_DEFAULT_PASSWORD}
      - STAGE=${STAGE}


  db:
    container_name: clean_architecture_db
    image: postgres:17.2-alpine3.20
    restart: always #en caso de errores o paros, se reinicia
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  pgAdmin:
    container_name: pgAdmin_clean_architecture
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    volumes:
     - ./db/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - 8080:80


